### ISSUE TITLE
Class-based rewrite with Scanner & Remote

### ISSUE THREAD

**Issue by WeeJeWel** [msloth/lgtv.js#16]
See here: https://github.com/WeeJeWel/node-webos

Just can't get a direct YouTube video to play - any advice?

**Comment by msloth** [comment]
Hey, nice lib! Sorry for late answer, not maintaining this as you know :)
Hope you already got it to work but otherwise you could look at the websocket traffic in wireshark and compare yours to mine. Hm, IIRC youtube works with mine, but don't really remember. Haven't really used it in a long time. Look at the example/test, it should have an example for youtube.

**Comment by msloth** [comment]
Ok, had a look, I can open the youtube-app but I don't know if going directly to a video works.

https://github.com/msloth/lgtv.js/blob/master/examples/open-youtube.js#L13

**Comment by msloth** [comment]
Oh yeah, here
https://github.com/msloth/lgtv.js/blob/4b6480711fb5f49c6efc4c1a44f0ec3d2898d561/tests/tests.js#L254
https://github.com/msloth/lgtv.js/blob/4b6480711fb5f49c6efc4c1a44f0ec3d2898d561/tests/tests.js#L620
